name: Deploy PHP Application to EC2

on:
  push:
    branches:
      - master # Replace this with your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and configure AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Deploy PHP application to EC2
        env:
          EC2_PUBLIC_IP: 35.154.225.147 # Replace this with your EC2 public IP
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          
          ssh-keyscan -H $EC2_PUBLIC_IP >> ~/.ssh/known_hosts
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@$35.154.225.147 "mkdir -p /var/www/html"
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} index.php ubuntu@$35.154.225.147:/var/www/html/
